### PR TITLE
Update ESLint version and config

### PR DESCRIPTION
**Pull request by dbrockman**
Use [shared eslint config](https://github.com/Springworks/eslint-config-springworks) instead of duplicating files.

### CODE REVIEW

**Comment by dbrockman** [comment]
- [x] Tweak rules a bit
- [x] Fix new linter issues until tests pass

**Comment by sommestad** [comment]
I think we should walk this through offline, it's hard to judge just by looking at the linter file. :)

**Comment by dbrockman** [comment]
Also all the rules are duplicated in several files.

**Comment by dbrockman** [comment]
- [x] Use [eslint-config-springworks](https://github.com/Springworks/eslint-config-springworks) instead.

**Pull request merged**
